### ISSUE TITLE
User is not informed if connection is not established.

### ISSUE THREAD

**Issue by godofgrunts** [you-win/obs-websocket-gd#14]
If you type your password in wrong, the user is not informed that there is an error nor does the "Connect" button change states.

In obs_websocket.gd we're calling `establish_connection` already. Currently we're only checking if it connects to the URL and _authenticate is getting information about the error ({error:Authentication Failed., message-id:3, status:error})

Websockets aren't something I'm super familiar with, so I'll play around with this for a bit, but I'm not 100% sure on how to approach this problem. Maybe handle it in `_on_data_received` and emit an error signal?

**Comment by you-win** [comment]
Fixed by #15 , probably
