### ISSUE TITLE
Plans on updating for obs-websockets 5?

### ISSUE THREAD

**Issue by godofgrunts** [you-win/obs-websocket-gd#16]
Found out today that obs-websocket 5 is going to break backward compatibility. See the [Important Notice!](https://github.com/obsproject/obs-websocket/releases/tag/4.9.1) section.

https://github.com/obsproject/obs-websocket/blob/master/docs/generated/protocol.md

**Comment by you-win** [comment]
Will just need to update once version 5 is released

**Comment by you-win** [comment]
@godofgrunts PR in progress for obs-websocket 5 #18 

It's pretty ugly right now but that's what refactoring is for ;)

**Comment by you-win** [comment]
#18 has been merged into master. The old 4.x version has been moved to the [obs-websocket_4.x](https://github.com/you-win/obs-websocket-gd/tree/obs-websocket_4.x) branch.

Work is still ongoing to testing the entire API from the Godot-side using [GUT](https://github.com/bitwes/Gut), but from my e2e tests, things seem to work.
