### ISSUE TITLE
Does this work with Godot 4.0?

### ISSUE THREAD

**Issue by TicklesTheBrain** [you-win/obs-websocket-gd#19]
If not, is there any chance for an update?

**Comment by you-win** [comment]
Currently this library will only work with Godot 3 but it shouldn't be too hard to convert to Godot 4. I will look into updating to Godot 4.0.

**Comment by you-win** [comment]
I've just pushed a godot-4 branch which may or may not work but the code loads in properly

**Comment by iznaut** [comment]
Has anyone had any luck getting this to work?

**Comment by you-win** [comment]
The godot-4 branch should work, is there something that isn't working?

**Comment by iznaut** [comment]
Yep - it seems to be an issue with WebSocketClient not existing in Godot 4?

<img width="542" alt="Screenshot 2023-05-01 at 11 14 16 PM" src="https://user-images.githubusercontent.com/36773942/235578044-aaaa399d-236a-41d1-9262-4aa07c4fdbc3.png">

I tried to hack around it a bit but I'm not super familiar with any of the WebSocket stuff. Maybe this is helpful? https://godotengine.org/qa/148763/godot-4-equivalent-of-websocketclients-get_peer

**Comment by you-win** [comment]
I have updated the library to (probably) work under Godot 4.0.2. I have only done minor testing (i.e. verified the connection + authentication to obs-websocket works) but in theory, it should work unless the obs-websocket 5.x api has changed as well

**Comment by iznaut** [comment]
Looks good so far! I'll report back if I run into any other roadblocks.

Thank you!

**Comment by you-win** [comment]
Closing since this should be solved.
