### ISSUE TITLE
Source enable/disable acts odd

### ISSUE THREAD

**Issue by captainwasabi** [you-win/obs-websocket-gd#7]
When you click on the switch by the source to enable/disable, it puts a Render swith in a panel above the scenes.  From there you can switch the source on and off. Also clicking on a source causes the switch states to change on all. it seems like clicking on the source panel is treating all the sources like a radio button group instead of a multi-select (maybe a copy/paste error from the scene list, because that is the way the scenes are supposed to work?  However, it isn't the switch shown in the source's list item that controls it.  The button labeled Render that appears at the top does that, but noither is showing an accurate state initially.

**Comment by tens0rcat** [comment]
Fixed
